ReportDefinitions:
- reportName: ArchitectMisReport
  decryptionPathId: ArchitectMisReport
  summary: Fetches Architect Details Report data based on provided search parameters
  version: 1.0.0
  moduleName: rainmaker-obps
  sourceColumns:
  - name: name
    label: Architect Name
    type: string
    source: obps
  - name: mobilenumber
    label: Contact No
    type: string
    source: obps
  - name: emailid
    label: Email Id
    type: string
    source: obps
  - name: validity
    label: Validity
    type: string
    source: obps 
  searchParams:
  - name: ulb
    label: ULB
    type: singlevaluelist
    pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
    source: obps
    wrapper: true
    isMandatory: false
    disabled: true
    searchClause: and usr.tenantid=$ulb
  query: select usr.name as name,usr.tenantid,usr.mobilenumber as mobilenumber,usr.emailid as emailid,usr.validitydate as validity,CASE
    WHEN rolev1.role_code='BPA_ARCHITECT' THEN 'Architect'
    WHEN rolev1.role_code='BPA_SUPERVISOR' THEN 'Supervisor'
	  WHEN rolev1.role_code='BPA_STRUCTURALENGINEER' THEN 'Structural Engineer'
	  WHEN rolev1.role_code='BPA_BUILDER' THEN 'Builder'
  END AS Designation from eg_user usr inner join eg_userrole_v1 rolev1 on usr.id=rolev1.user_id where rolev1.role_code in ('BPA_ARCHITECT','BPA_SUPERVISOR','BPA_STRUCTURALENGINEER','BPA_BUILDER')
 
    
    

 
