ReportDefinitions: 
- reportName: ArchitectMisReport
  decryptionPathId: ArchitectMisReport
  summary: Fetches Architect Details Report data based on provided search parameters
  version: 1.0.0
  moduleName: rainmaker-obps
  sourceColumns:
  - name: name
    label: Architect Name
    type: string
    source: obps
  - name: mobilenumber
    label: Contact No
    type: string
    source: obps
  - name: emailid
    label: Email Id
    type: string
    source: obps
  - name: validity
    label: Validity
    type: string
    source: obps
  - name: Designation
    label: Designation
    type: string
    source: obps 
  searchParams:
  - name: ulb
    label: ULB
    type: singlevaluelist
    pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
    source: obps
    wrapper: true
    isMandatory: false
    disabled: true
    searchClause: and usr.tenantid=$ulb
  query: select usr.name as name,usr.tenantid,usr.mobilenumber as mobilenumber,usr.emailid as emailid,TO_CHAR(usr.validitydate, 'DD/MM/YYYY') AS validity,
        CASE
         WHEN rolev1.role_code='BPA_ARCHITECT' THEN 'Architect'
         WHEN rolev1.role_code='BPA_SUPERVISOR' THEN 'Supervisor'
         WHEN rolev1.role_code='BPA_STRUCTURALENGINEER' THEN 'Structural Engineer'
         WHEN rolev1.role_code='BPA_BUILDER' THEN 'Builder'
         WHEN rolev1.role_code='BPA_ENGINEER' THEN 'Engineer'
         END AS Designation from eg_user usr inner join eg_userrole_v1 rolev1 on usr.id=rolev1.user_id where rolev1.role_code in ('BPA_ARCHITECT','BPA_SUPERVISOR','BPA_STRUCTURALENGINEER','BPA_BUILDER','BPA_ENGINEER')
 
- reportName: ApplicationStatusReport
  decryptionPathId: ApplicationStatusReport
  summary: Fetches application data based on provided search parameters
  version: 1.0.0
  moduleName: rainmaker-obps
  sourceColumns:
  - name: Applicationno
    label: Application No
    type: string
    source: obps
  - name: name
    label: Architect Name
    type: string
    source: obps 
  - name: username
    label: Owner Name
    type: string
    source: obps
    isLocalisationRequired: true
    localisationPrefix:
  - name: applicationdate
    label: Application Date
    type: string
    source: obps
    isLocalisationRequired: true
    localisationPrefix:
  - name: approvaldate
    label: Approval Date
    type: string
    source: obps
    isLocalisationRequired: true
    localisationPrefix: 
  - name: status
    label: status
    type: string
    source: obps
    isLocalisationRequired: true
    localisationPrefix:
  searchParams:
  - name: ulb
    label: ULB
    type: singlevaluelist
    pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
    source: obps
    wrapper: true
    isMandatory: true
    searchClause: AND bp.tenantid = $ulb
  - name: fromDate
    label: FromDate
    type: epoch
    source: obps
    isMandatory: false
    searchClause: AND bp.createdtime >= $fromDate
  - name: toDate
    label: ToDate
    type: epoch
    source: obps
    isMandatory: false
    searchClause: AND bp.createdtime  <= $toDate  
  query: SELECT applicationno as Applicationno, bp.tenantid, Architectuser.name as name,Citizenuser.name as username,TO_CHAR(TO_TIMESTAMP(bp.createdtime / 1000), 'DD/MM/YYYY') AS applicationdate,CASE WHEN bp.approvaldate = 0 THEN NULL ELSE TO_CHAR(TO_TIMESTAMP(bp.approvaldate / 1000), 'DD/MM/YYYY') END AS approvaldate,
        CASE 
        WHEN bp.status='DOC_VERIFICATION_PENDING_BY_ENGINEER' OR bp.status='DOC_VERIFICATION_INPROGRESS_BY_ENGINEER' THEN 'Pending at Sub-Engineer'
        WHEN bp.status='DOC_VERIFICATION_INPROGRESS_BY_BUILDER' THEN 'Pending at Building Officer'
        WHEN bp.status='POST_FEE_APPROVAL_INPROGRESS' THEN 'Approved by Building officer'
        WHEN bp.status='APPROVAL_INPROGRESS' THEN 'Pending at final authority'
        WHEN bp.status='PENDING_SANC_FEE_PAYMENT' THEN 'Approved by final Authority and pending post fee'
        WHEN bp.status='APPROVED' THEN 'Post fee paid and issued permit order'
    END AS status
    FROM eg_bpa_buildingplan bp INNER JOIN eg_user Architectuser ON bp.createdby = Architectuser.uuid INNER JOIN eg_land_ownerinfo ownerinfo ON bp.landid = ownerinfo.landinfoid INNER JOIN eg_user Citizenuser ON ownerinfo.uuid = Citizenuser.uuid 
    where bp.status in('DOC_VERIFICATION_PENDING_BY_ENGINEER','DOC_VERIFICATION_INPROGRESS_BY_ENGINEER', 'DOC_VERIFICATION_INPROGRESS_BY_BUILDER','POST_FEE_APPROVAL_INPROGRESS','APPROVAL_INPROGRESS','PENDING_SANC_FEE_PAYMENT','APPROVED')
    
- reportName: bpaApplicationStatusReport
  decryptionPathId: bpaApplicationStatusReport
  summary: Fetches bpa data based on provided search parameters
  version: 1.0.0
  moduleName: rainmaker-bpa
  sourceColumns:
  - name: applicationno
    label: Application No
    type: string
    source: bpa
  - name: applicationdate
    label: Application Date
    type: string
    source: bpa 
  - name: approval_date
    label: Approval Date
    type: string
    source: bpa
    isLocalisationRequired: true
    localisationPrefix:
  - name: username
    label: Applicant Name
    type: string
    source: bpa
    isLocalisationRequired: true
    localisationPrefix: 
  - name: altcontactnumber
    label: Applicant Contact No.
    type: string
    source: bpa
    isLocalisationRequired: true
    localisationPrefix:
  - name: emailid
    label: Applicant Emailid
    type: string
    source: bpa
    isLocalisationRequired: true
    localisationPrefix:
  - name: name
    label: Owner Name
    type: string
    source: bpa
    showColumn: true
    isLocalisationRequired: true
  - name: mobilenumber
    label: Owner Contact No.
    type: string
    source: bpa
    showColumn: true
  - name: khatano
    label: Khasra No
    type: string
    source: bpa
  - name: city
    label: City
    type: string
    source: bpa
  - name: plotno
    label: Plot No
    type: string
    source: bpa
  - name: plotarea
    label: Plot Area
    type: string
    source: bpa
  - name: occupancy_type
    label: Occupancy Type
    type: string
    source: bpa
  - name: patwari_halka_no
    label: Patwari Halka No.
    type: string
    source: bpa
  - name: prefees
    label: Pre payment Amount
    type: string
    source: bpa
  - name: postfees
    label: Post Payment Amount
    type: string
    source: bpa
  - name: status
    label: Application Status
    type: string
    source: bpa
  - name: Building_permission_certificate
    label: Building permission Certificate Issued date
    type: string
    source: bpa	
  searchParams:
  - name: ulb
    label: ULB
    type: singlevaluelist
    pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
    source: bpa
    wrapper: true
    isMandatory: true
    searchClause: AND bp.tenantid = $ulb
  - name: fromDate
    label: FromDate
    type: epoch
    source: bpa
    isMandatory: false
    searchClause: AND bp.createdtime >= $fromDate
  - name: toDate
    label: ToDate
    type: epoch
    source: bpa
    isMandatory: false
    searchClause: AND bp.createdtime  <= $toDate  
  query: SELECT 
        billdetail.consumercode as applicationno, 
        bp.tenantid, 
        TO_CHAR(
        TO_TIMESTAMP(bp.createdtime / 1000), 
        'DD/MM/YYYY'
        ) AS applicationdate, 
        TO_CHAR(
        TO_TIMESTAMP(bp.approvaldate / 1000), 
      'DD/MM/YYYY'
      ) AS approval_date, 
        Architectuser.uuid as uuid, 
        Architectuser.name AS username,
        Architectuser.mobilenumber AS altcontactnumber,
        Architectuser.emailid as emailid, 
        STRING_AGG(DISTINCT Citizenuser.name, ', ') AS name, 
        STRING_AGG(DISTINCT Citizenuser.mobilenumber, ', ') AS mobilenumber, 
        adr.khataNo as khatano, 
        adr.mauza AS city, 
        adr.plotno as plotno, 
        adr.plotArea as plotarea, 
        adr.occupancy AS occupancy_type, 
        adr.patwarihn AS patwari_halka_no, 
        SUM(
          CASE WHEN billdetail.businessservice = 'BPA.NC_APP_FEE' THEN billdetail.totalamount ELSE 0 END
        ) AS prefees, 
        SUM(
          CASE WHEN billdetail.businessservice = 'BPA.NC_SAN_FEE' THEN billdetail.totalamount ELSE 0 END
        ) AS postfees, 
        CASE WHEN bp.status = 'APPROVED' THEN 'Approved' WHEN bp.status IN(
          'PENDING_APPL_FEE', 'DOC_VERIFICATION_PENDING_BY_ENGINEER', 
          'DOC_VERIFICATION_INPROGRESS_BY_BUILDER', 
          'APPROVAL_INPROGRESS', 'DOC_VERIFICATION_INPROGRESS_BY_ENGINEER', 
          'POST_FEE_APPROVAL_INPROGRESS', 
          'PENDING_SANC_FEE_PAYMENT', 'CITIZEN_ACTION_PENDING_AT_DOC_VERIF'
        ) THEN 'Pending' WHEN bp.status = 'REJECTED' THEN 'Rejected' END AS status, 
        TO_CHAR(
          TO_TIMESTAMP(bp.approvaldate / 1000), 
          'DD/MM/YYYY'
        ) AS Building_permission_certificate 
        FROM 
          egbs_billdetail_v1 billdetail 
          INNER JOIN eg_bpa_buildingplan bp ON billdetail.consumercode = bp.applicationno 
          INNER JOIN eg_pg_transactions txn on billdetail.billid = txn.bill_id 
          INNER JOIN eg_land_address adr ON adr.landinfoid = bp.landid 
          INNER JOIN eg_user Architectuser ON bp.createdby = Architectuser.uuid 
          INNER JOIN eg_land_ownerinfo ownerinfo ON bp.landid = ownerinfo.landinfoid 
          INNER JOIN eg_user Citizenuser ON ownerinfo.uuid = Citizenuser.uuid 
        WHERE 
          1 = 1 
          AND bp.status IN (
            'APPROVED', 'REJECTED', 'PENDING_APPL_FEE', 
            'DOC_VERIFICATION_PENDING_BY_ENGINEER', 
            'DOC_VERIFICATION_INPROGRESS_BY_BUILDER', 
            'APPROVAL_INPROGRESS', 'DOC_VERIFICATION_INPROGRESS_BY_ENGINEER', 
            'POST_FEE_APPROVAL_INPROGRESS', 
            'PENDING_SANC_FEE_PAYMENT', 'CITIZEN_ACTION_PENDING_AT_DOC_VERIF'
          ) 
          AND txn.txn_status = 'SUCCESS'
  groupby: GROUP BY 
            billdetail.consumercode, 
            bp.createdtime, 
            bp.approvaldate, 
            Architectuser.emailid, 
            adr.khataNo, 
            adr.plotno, 
            adr.plotArea, 
            occupancy_type, 
            patwari_halka_no, 
            adr.mauza, 
            bp.status, 
            bp.tenantid, 
            Architectuser.uuid,
            Architectuser.name,
            Architectuser.mobilenumber
  orderby: order by billdetail.consumercode 
    

 
