ReportDefinitions:
- reportName: ArchitectMisReport
  decryptionPathId: ArchitectMisReport
  summary: Fetches Architect Details Report data based on provided search parameters
  version: 1.0.0
  moduleName: rainmaker-bpa
  sourceColumns:
  - name: Architectname
    label: Architect Name
    type: string
    source: bpa
  - name: contactno
    label: Contact No
    type: string
    source: bpa
  - name: emailid
    label: Email Id
    type: string
    source: bpa
  - name: validity
    label: Validity
    type: string
    source: bpa 
  searchParams:
  - name: ulb
    label: ULB
    type: singlevaluelist
    pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
    source: bpa
    wrapper: true
    isMandatory: true
    disabled: true
    searchClause: AND usr.usertenantid = $ulb
  query: select usr.username as Architectname,usr.usertenantid,usr.mobilenumber as contactno,usr.emailid as emailid,usr.validitydate as validity from eg_user usr inner join eg_userrole_v1 rolev1 on usr.id=rolev1.user_id where rolev1.role_code='BPA_ARCHITECT'
 
    
    

 
