ReportDefinitions:
- reportName: bpaApplicationStatusReport
  decryptionPathId: bpaApplicationStatusReport
  summary: Fetches bpa data based on provided search parameters
  version: 1.0.0
  moduleName: rainmaker-bpa
  externalService:
  - entity: $.messages
    apiURL: https://www.niwaspass.com/localization/messages/v1/_search?module=rainmaker-cg.birgaon&locale=en_IN&tenantId=cg.birgaon
    keyOrder: code,message
    tableName: public.message
  sourceColumns:
  - name: applicationno
    label: Application No
    type: string
    source: bpa
  - name: applicationdate
    label: Application Date
    type: string
    source: bpa
  - name: uuid
    label: uuid
    type: string
    source: bpa
    showColumn: false
    isLocalisationRequired: true
    localisationPrefix: 
  - name: name
    label: Name
    type: string
    source: bpa
    isLocalisationRequired: true
    localisationPrefix: 
  - name: applicationtype
    label: Application Type
    type: string
    source: bpa
    isLocalisationRequired: true
    localisationPrefix: 
  - name: servicetype
    label: Service Type
    type: string
    source: bpa
    isLocalisationRequired: true
    localisationPrefix: 
  - name: occupancytype
    label: Occupancy Type
    type: string
    source: bpa
    showColumn: true
  - name: status
    label: Status
    type: string
    source: bpa
    showColumn: true
    isLocalisationRequired: true
  - name: currentowner
    label: Current Owner
    type: string
    source: bpa
    showColumn: true
  searchParams:
  - name: fromDate
    label: FromDate
    type: epoch
    source: bpa
    isMandatory: false
    searchClause: AND bp.createdtime >= $fromDate
  - name: toDate
    label: ToDate
    type: epoch
    source: bpa
    isMandatory: false
    searchClause: AND bp.createdtime  <= $toDate
  - name: applicationChannel
    label: reports.bpa.applicationchannel
    type: multivaluelist
    source: bpa
    isMandatory: false
    searchClause: AND landinfo.channel in ( $applicationChannel )
    pattern: 'list://SYSTEM:SYSTEM'
    isLocalisationRequired: true
    localisationPrefix: REPORT_bpa_
  - name: applicationType
    label: reports.bpa.applicationtype
    type: multivaluelist
    source: bpa
    isMandatory: false
    pattern: 'list://BUILDING_OC_PLAN_SCRUTINY:BUILDING_OC_PLAN_SCRUTINY,BUILDING_PLAN_SCRUTINY:BUILDING_PLAN_SCRUTINY'
    searchClause: AND bp.additionaldetails->>'applicationType' in ( $applicationType )
    isLocalisationRequired: true
    localisationPrefix: REPORT_bpa_
  - name: serviceType
    label: reports.bpa.servicetype
    type: multivaluelist
    source: bpa
    isMandatory: false
    pattern: 'list://NEW_CONSTRUCTION:NEW_CONSTRUCTION'
    searchClause: AND bp.additionaldetails->> 'serviceType' in ( $serviceType )
    isLocalisationRequired: true
    localisationPrefix: REPORT_bpa_
  - name: status
    label: reports.bpa.status
    type: multivaluelist
    source: bpa
    isMandatory: false
    pattern: 'list://CITIZEN_ACTION_PENDING_AT_DOC_VERIF:CITIZEN_ACTION_PENDING_AT_DOC_VERIF,INPROGRESS:INPROGRESS,PENDING_APPL_FEE:PENDING_APPL_FEE,PENDING_SANC_FEE_PAYMENT:PENDING_SANC_FEE_PAYMENT,DOC_VERIFICATION_INPROGRESS:DOC_VERIFICATION_INPROGRESS,CITIZEN_ACTION_PENDING_AT_NOC_VERIF:CITIZEN_ACTION_PENDING_AT_NOC_VERIF,PERMIT REVOCATION:PERMIT REVOCATION,FIELDINSPECTION_INPROGRESS:FIELDINSPECTION_INPROGRESS,PENDING_FEE:PENDING_FEE,NOC_VERIFICATION_INPROGRESS:NOC_VERIFICATION_INPROGRESS,INITIATED:INITIATED,CITIZEN_APPROVAL_INPROCESS:CITIZEN_APPROVAL_INPROCESS,REJECTED:REJECTED,APPROVED:APPROVED,CITIZEN_ACTION_PENDING_AT_FI_VERIF:CITIZEN_ACTION_PENDING_AT_FI_VERIF,APPROVAL_INPROGRESS:APPROVAL_INPROGRESS'
    searchClause: AND bp.status in ( $status )
    isLocalisationRequired: true
    localisationPrefix: REPORT_bpa_

  query: select distinct bp.applicationno,to_char(To_timestamp(bp.createdtime / 1000), 'DD/MM/YYYY') as applicationdate, landinfo.channel as applicationchannel, usr.name as name,  usr.uuid as uuid, bp.additionaldetails->>'applicationType' as applicationtype, bp.additionaldetails->> 'serviceType' as servicetype, land.occupancytype, bp.status, case when isterminatestate=true then null else userassignee.name end as currentowner, bp.approvalno as permitno FROM eg_wf_state_v2 st inner join eg_wf_processinstance_v2 pi on pi.status=st.uuid inner join eg_bpa_buildingplan bp on pi.businessid=bp.applicationno inner join eg_user usr ON bp.createdby = usr.uuid  inner join eg_land_unit land ON land.landinfoid = bp.landid inner join eg_land_landinfo landinfo ON land.landinfoid = landinfo.id inner join eg_land_address adr ON adr.landinfoid = landinfo.id inner join eg_user userassignee ON assigner = userassignee.uuid LEFT JOIN public.message messagekey ON messagekey.code = bp.status WHERE 1=1
 
  
- reportName: MisPendencyReport
  decryptionPathId: MisPendencyReport
  summary: fetch pending applications
  version: 1.0.0
  moduleName: rainmaker-bpa
  sourceColumns:
  - name: Pending_by_subengineer
    label: Pending by Sub Engineer
    type: string
    source: bpa
  - name: Pending_by_Builder
    label: Pending by Builder
    type: string
    source: bpa
  - name: Pending_by_commissioner
    label: Pending by Commissioner
    type: string
    source: bpa
    isLocalisationRequired: true
    localisationPrefix: ""
  - name: Pending_by_architect
    label: Pending by Architect
    type: string
    source: bpa
    isLocalisationRequired: true
    localisationPrefix: ""
  - name: Total_pending_cases
    label: Total Pending Cases
    type: string
    source: bpa
    isLocalisationRequired: true
    localisationPrefix: ""
  searchParams:
  - name: fromDate
    label: FromDate
    type: epoch
    source: bpa
    isMandatory: false
    searchClause: AND 1=1
  - name: toDate
    label: ToDate
    type: epoch
    source: bpa
    isMandatory: false
    searchClause: AND 1=1

  query: select Pending_by_subengineer,  Pending_by_Builder, Pending_by_commissioner, Pending_by_architect, (Pending_by_subengineer + Pending_by_Builder + Pending_by_commissioner + Pending_by_architect ) as Total_pending_cases from (
        SELECT
      COUNT(CASE WHEN status = 'DOC_VERIFICATION_PENDING_BY_ENGINEER' THEN 1 END) AS Pending_by_subengineer,
      COUNT(CASE WHEN status = 'DOC_VERIFICATION_INPROGRESS_BY_ENGINEER' THEN 1 END) AS Pending_by_Builder,
      COUNT(CASE WHEN status = 'PENDINGAPPROVAL' THEN 1 END) AS Pending_by_commissioner,
      COUNT(CASE WHEN status = 'PENDING_APPL_FEE' THEN 1 END) AS Pending_by_architect
      FROM  eg_bpa_buildingplan WHERE createdtime >= $fromDate) as t WHERE 1=1
  
- reportName: HistoryMisReport
  decryptionPathId: HistoryMisReport
  summary: Fetches History Mis Report data based on provided search parameters
  version: 1.0.0
  moduleName: rainmaker-bpa
  sourceColumns:
  - name: Application_no
    label: Application No
    type: string
    source: bpa
  - name: name
    label: Applicant Name
    type: string
    source: bpa
  - name: Application_date
    label: Application Date
    type: string
    source: bpa
  - name: status
    label: Status
    type: string
    source: bpa
    isLocalisationRequired: true
    localisationPrefix:
  - name: plotno
    label: Plot No
    type: string
    source: bpa
    isLocalisationRequired: true
    localisationPrefix: 
  - name: mobilenumber
    label: Mobile Number
    type: string
    source: bpa
    isLocalisationRequired: true
    localisationPrefix:
  - name: khataNo
    label: KhataNo
    type: string
    source: bpa
    isLocalisationRequired: true
    localisationPrefix: EGOV_HRMS_EMPLOYEESTATUS_
  - name: City
    label: City
    type: string
    source: bpa
    isLocalisationRequired: true
    localisationPrefix:
  - name: plotArea
    label: PlotArea
    type: string
    source: bpa
    isLocalisationRequired: true
    localisationPrefix:
  - name: occupancy
    label: Occupancy
    type: string
    source: bpa
    isLocalisationRequired: true
    localisationPrefix:
  searchParams:
  - name: fromDate
    label: FromDate
    type: epoch
    source: bpa
    isMandatory: false
    searchClause: AND bp.createdtime >= $fromDate
  - name: toDate
    label: ToDate
    type: epoch
    source: bpa
    isMandatory: false
    searchClause: AND bp.createdtime  <= $toDate
  query: select applicationno as Application_no, usr.name as name,to_char(To_timestamp(bp.createdtime / 1000), 'DD/MM/YYYY') as Application_date, status, mobilenumber, khataNo, mauza as City, plotno, plotArea, occupancy from eg_bpa_buildingplan bp inner join eg_land_address adr on adr.landinfoid=bp.landid inner join eg_user usr on usr.uuid=bp.createdby where 1=1
  order by: ORDER BY Application_date ASC

 
