ReportDefinitions:
- reportName: ArchitectMisReport
  decryptionPathId: ArchitectMisReport
  summary: Fetches Architect Details Report data based on provided search parameters
  version: 1.0.0
  moduleName: rainmaker-obps
  sourceColumns:
  - name: name
    label: Architect Name
    type: string
    source: obps
  - name: mobilenumber
    label: Contact No
    type: string
    source: obps
  - name: emailid
    label: Email Id
    type: string
    source: obps
  - name: validity
    label: Validity
    type: string
    source: obps 
  searchParams:
  - name: ulb
    label: ULB
    type: singlevaluelist
    pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
    source: obps
    wrapper: true
    isMandatory: false
    disabled: true
    searchClause: AND usr.tenantid = $ulb
  query: select usr.name as nameselect usr.name as name,usr.tenantid,usr.uuid,usr.mobilenumber as mobilenumber,usr.emailid as emailid,usr.validitydate as validity from eg_user usr inner join eg_userrole_v1 rolev1 on usr.id=rolev1.user_id where rolev1.role_code='BPA_ARCHITECT';,usr.uuid,usr.mobilenumber as mobilenumber,usr.emailid as emailid,usr.validitydate as validity from eg_user usr inner join eg_userrole_v1 rolev1 on usr.id=rolev1.user_id where rolev1.role_code='BPA_ARCHITECT'
 
    
    

 
